### ISSUE TITLE
help, build failed

### ISSUE THREAD

**Issue by roundtwo** [wbsoft/python-poppler-qt4#6]
wb, thanks for your great work!

when I build , I failed

E:\zhichunlu_libs\python-poppler-qt4-0.18.1>setup.py build
Traceback (most recent call last):
  File "E:\zhichunlu_libs\python-poppler-qt4-0.18.1\setup.py", line 56, in <modu
le>
    import PyQt4.pyqtconfig
ImportError: No module named pyqtconfig

 I found that in Pyqt 4.10 and above, pyqtconfig.py seems be removed.
http://stackoverflow.com/questions/17967542/python-importerror-pyqtconfig/18865570#18865570
http://pyqt.sourceforge.net/Docs/PyQt4/build_system.html#module-PyQt4.pyqtconfig

Versions of sip, qt,pyqt are:4.16.5 , 4.8.6 , 4.11.3 
>>> from PyQt4.Qt import *
>>> from sip import *
>>> print SIP_VERSION_STR, QT_VERSION_STR, PYQT_VERSION_STR
4.16.5 4.8.6 4.11.3 

please ,can you do something to fix it ?

**Comment by wbsoft** [comment]
Sorry, this was fixed already in git. Now 0.18.2 (see https://pypi.python.org/pypi/python-poppler-qt4) contains the fix.

**Comment by roundtwo** [comment]
thanks!
