### ISSUE TITLE
install success，but import error！

### ISSUE THREAD

**Issue by roundtwo** [wbsoft/python-poppler-qt4#7]
I have installed python-poppler-qt4. But when import popplerqt4, a error occured.

please help me, thank you!

My computer os: Windows7, Qt:4.8.6, poppler:0.30.0

==============
Processing dependencies for python-poppler-qt4==0.18.2
Finished processing dependencies for python-poppler-qt4==0.18.2

E:\zhichunlu_libs\python-poppler-qt4-0.18.2>python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> from PyQt4 import QtGui
>>> import popplerqt4
C:\Python27\lib\site-packages\python_poppler_qt4-0.18.2-py2.7-win32.egg\popplerq
t4.py:3: UserWarning: Module popplerqt4 was already imported from C:\Python27\li
b\site-packages\python_poppler_qt4-0.18.2-py2.7-win32.egg\popplerqt4.pyc, but e:
\zhichunlu_libs\python-poppler-qt4-0.18.2 is being added to sys.path
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\popplerqt4.py", line 7, in <module>
  File "build\bdist.win32\egg\popplerqt4.py", line 6, in __bootstrap__
ImportError: DLL load failed: 找不到指定的程序。
>>>

**Comment by wbsoft** [comment]
are all the libraries (qt4, poppler-qt4 etc) in your $PATH ?

**Comment by wbsoft** [comment]
I think python-poppler-qt4 does not automatically download and install Qt4, PyQt4 and poppler-qt4. Those should be downloaded and installed separately.

**Comment by roundtwo** [comment]
I fixed this problem, thank you!
